function init(self)
	msg.post(".", "acquire_input_focus")

	-- rotate the cube and the point light
	go.animate(".", "euler.y", go.PLAYBACK_LOOP_FORWARD, 360, go.EASING_INOUTQUAD, 6)

	-- tint the spheres
	go.set("/spheres#right", "tint", vmath.vector4(0,0.5,1,1))
	go.set("/spheres#left", "tint", vmath.vector4(1,0.5,0,1))

	self.light_rotation_start = go.get_rotation("/spot")
	self.light_rotation = vmath.vector3()
end

function update(self, dt)
	-- apply the light rotation to the spotlight
	local spot_rotation_offset = vmath.euler_to_quat(self.light_rotation.x, self.light_rotation.y, 0)
	go.set_rotation(self.light_rotation_start * spot_rotation_offset, "/spot")
end

function on_input(self, action_id, action)
	self.light_rotation.x = vmath.clamp(self.light_rotation.x + action.dy/10, -35, 35)
	self.light_rotation.y = vmath.clamp(self.light_rotation.y - action.dx/10, -35, 35)
end